name: SAST with CodeQL

on:
  push:
    branches: [main, sast]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Snyk Test
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
      - name: Run Snyk to check for vulnerabilities
        if: always()
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Run CodeQL analysis
        if: always()
        uses: github/codeql-action/analyze@v3
        with: 
          category: security
          output: results.sarif

      - name: Show CodeQL results
        if: always()
        run: |
          echo "CodeQL Analysis Results:"
          cat /home/runner/work/sast/sast/results.sarif/python.sarif

      - name: Install Bandit
        if: always()
        run: |
          pip install bandit

      - name: Run Bandit
        if: always()
        run: |
          bandit -r . -f json -o bandit-results.json

      - name: Show Bandit results
        if: always()
        run: |
          cat bandit-results.json
