name: SAST with CodeQL

on:
  push:
    branches: [main, sast]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sast:
    name: sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: python # Choose your language (e.g., python, java, etc.)
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: security
          output: results.sarif
