name: Spring Boot CI

on:
  push:
    branches: [main, sast]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'    # Specify Java version, adjust as needed
        distribution: 'temurin'  # Using Eclipse Temurin (Adoptium) distribution

    - name: Build with Gradle
      run: gradle build

    - name: Run Tests
      run: gradle test

    - name: Run the Application
      run: |
        nohup java -javaagent:"./raspdemo/rasp/rasp/rasp.jar" -jar ./raspdemo/build/libs/your-app-name-0.0.1-SNAPSHOT.jar 
        echo "Application is running"